spring:
  application:
    name: forum
  datasource:
    url: jdbc:postgresql://localhost:5432/unespiano
    username: postgres
    password: 12345
    ddl-auto: create-drop
server:
  port: 9094


eureka:
  instance:
    hostname: localhost
    port: 8761
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
